FROM alpine

RUN apk update && \
  apk upgrade && \
  apk add --no-cache bash vim python3 python3-dev build-base && \
  pip3 install -U --no-cache-dir pip && \
  pip3 install -U spacy webvtt-py flask flask-cors && \
  python3 -m spacy download en

WORKDIR lingua
COPY ./src/*.py ./
ENV FLAS_APP=server.py
CMD python3 -m flask run --host=0.0.0.0
